### ISSUE TITLE
Blurry images & mobile responsiveness

### ISSUE THREAD

**Issue by SilverFoxA** [nehasolulab/ui#4]
Overall, the project structure and usage of components look good. Here are a few key issues, these are primarily to do with the mobile responsiveness & images.

![Screenshot 2023-02-13 at 11 17 39 AM](https://user-images.githubusercontent.com/6983070/218381136-1c96ad84-9e30-4919-9dee-9c37d39ca733.png)
![Screenshot 2023-02-13 at 11 18 02 AM](https://user-images.githubusercontent.com/6983070/218381148-9698a291-4c14-4c8c-9fbf-7705adab50a8.png)
![Screenshot 2023-02-13 at 11 18 52 AM](https://user-images.githubusercontent.com/6983070/218381159-a7cd79e1-8b30-4a2f-b55b-315cdaf845c8.png)

**Comment by nehasolulab** [comment]
Hi @SilverFoxA ,
Sorry as on last time i forgot to check responsiveness of UI.
Fixed the issue that you pointed out, please check again.
Here is a video link of fixed issue:
https://www.loom.com/share/a5bd568ee14e4779a521e6d1ee9b54a2
